server:
  port: 9020
# 数据库配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rongcloudtestdatabase?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
swagger:
  enabled: true
rongcloud:
  im:
    appKey: c9kqb3rdc6thj
    appSecret: OPxgxvq7ZqT3




